project:
  type: website
  execute-dir: project

website:
  title: "Kentaro Kamada"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: profile.qmd
        text: "Profile"
      - href: research.qmd
        text: "Research"
      - text: "Works"
        menu: 
          - href: https://kentaro-kamada.github.io/kamaken/index.html
            text: "R Package: kamaken"
            target: _blank
          - href: https://kentaro-kamada.github.io/jisshutools/index.html
            text: "R Package: jisshutools"
            target: _blank
          - href: https://github.com/Kentaro-Kamada/hyoron-style
            text: "Latex Package: hyoron-style"
            target: _blank
      - href: blog/index.qmd
        text: "Blog"
    tools:
      - icon: github
        href: https://github.com/Kentaro-Kamada/Kentaro-Kamada.github.io

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    link-external-newwindow: true


bibliography: reference.bib

execute: 
  warning: false
  message: false
  freeze: auto

