project:
  type: website
  execute-dir: project

website:
  title: "Kentaro Kamada"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: profile.qmd
        text: "Profile"
      - href: research.qmd
        text: "Research"
      - href: blog/index.qmd
        text: "Blog"
    tools:
      - icon: github
        href: https://github.com/Kentaro-Kamada/Kentaro-Kamada.github.io

format:
  html:
    theme: yeti
    css: styles.css
    toc: true


bibliography: reference.bib

execute: 
  warning: false
  message: false
  freeze: auto

